### ISSUE TITLE
Other Chen et al probes

### ISSUE THREAD

**Issue by azzaea** [sirselim/illumina450k_filtering#2]
Hello @sirselim ,

Thank you for hosting the lists of reactive probes from Chen et al 2013 paper in this repo. The host website seems to have been redesigned recently, and they are nowhere to be found there.

I was curious though if by any chance you also curate their list of polymorphic probes- or know of such a mirror?

Best,
Azza

**Comment by sirselim** [comment]
Hi @azzaea - I don't have the Chen _et al_ list of polymorphic probes sorry. 

This is just my opinion, but I don't recommend filtering out SNP probes before analysis of 450k/850k array's, especially if you don't have a good grasp of the genetic variation of the population(s) you might be working with. I feel it's safer to perform any filtering down stream rather than 'throwing away' a very large proportion of the methylation data before the analysis, much of which is due to rare variation (SNPs) that are probably not having any influence on the results. 

Saying that, it is not hard to create your own file of 'polymorphic probes' by cross-referencing the array probes against resource such as dbSNP and GnomAD. I did something like this years ago, you can find the results in [this repository](https://github.com/sirselim/cpg_annotate) if you are interested. I was only interested in the CpG sites that had a SNP on either the C or the G, so my files don't indicate whether there is a SNP the base before the C, or for that matter if there are other SNPs in the 50 mer that makes up each probe (all things that might be important if you consider that SNP polymorphism can influence probe hybridisation).

If you are interested in identifying SNPs independent of public databases (potentially useful if your 'population' group(s) aren't well represented) then you might look at the `MethylToSNP` package described in this paper:
> LaBarre, B.A., Goncearenco, A., Petrykowska, H.M. et al. **_MethylToSNP: identifying SNPs in Illumina DNA methylation array data._** Epigenetics & Chromatin 12, 79 (2019). https://doi.org/10.1186/s13072-019-0321-6

Here is the GitHub repo for MethylToSNP ([link](https://github.com/elnitskilab/MethylToSNP)).

Hopefully this is helpful.

 - Miles

**Comment by azzaea** [comment]
Thank you very much Miles! I was looking for advice of this kind, appreciated.

Kindest regards,
Azza

**Comment by sirselim** [comment]
No problem at all.
