### ISSUE TITLE
Run before or after normalisation?

### ISSUE THREAD

**Issue by pedrodcb** [sirselim/illumina450k_filtering#6]
Hello, you mention in the README that these filtering steps must be run during the QC stage of an analysis. Yet in the code the beta value object used is named `beta_norm`. Should the beta values used be computed before or after normalisation?

Using minfi:

Exemple code for normalization:
`mSetSq <- preprocessQuantile(RGSet)`

Exemple code to get beta values after normalisation:
`beta_norm <- getBeta(mSetSq)`

Exemple code to get beta values after normalisation:
`beta_norm <- getBeta(RGSet)`

Thank you.

**Comment by sirselim** [comment]
Are you referring to the comment below?
> A collection of resources to filter 'bad'/cross-reactive/variant probes from the Illumina methylation arrays during QC stages of pipelines/analysis.

Because if so, I consider the filtering process to still be part of QC, so the statement is saying that this process is part of the whole QC process. Just because normalisation has happened it doesn't mean the QC has finished. I hope this makes sense.

As an aside, I haven't worked on methylation array's for many years and this process is likely quite outdated now - I wouldn't be surprised if packages such as `minfi` have the ability to do all of this type of filtering built in now.
